
send_interval: 10
sleep: 2
admin_number: +255767199999
location: 'Mbarara, Uganda'

my-number: 0788911892
database: 
  type: sqlite
  file: sms_timer.db
  
modems:
  mtn:
    number: '+256789906279'
    port: '/dev/ttyUSB2'
    baudrate: 115200
    send_to_self: true
    sent_count: 0
    # command to look up credit amount on mtn network
    credit_command: 'at+cusd=1,"*156#"'
    # parse results
    credit_re: 'UGX (\d+).'
  orange:
    number: '+256791929964'
    port: '/dev/ttyUSB1'
    baudrate: 115200
    send_to_self: true
    sent_count: 0
    # command to look credit amount on orange
    credit_command: 'at+cusd=1,"*131#"'
    # parse results
    credit_re: '(\d+) shillings,'
